---
- name: "install dns"
  ansible.builtin.yum:
    name: dnsmasq
    state: latest

- name: "modify dns configuration"
  ansible.builtin.template:
    src: dns.j2
    dest: /etc/dnsmasq.d/dns.conf
  notify:
  - restart dns
