---
- name: Install DNS
  ansible.builtin.yum:
    name: dnsmasq
    state: latest

- name: Modify DNS configuration
  ansible.builtin.template:
    src: dns.j2
    dest: /etc/dnsmasq.d/dns.conf
  notify:
  - restart dns

- name: Force DNS service restart for DNS check tasks
  ansible.builtin.meta: flush_handlers

# - name: Update nic dns setting
