---
- name: install haproxy
  ansible.builtin.yum:
    name: haproxy
    state: latest

- name: modify haproxy configuration
  ansible.builtin.template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
  - restart haproxy
