---
# - name: "install kvm"

- name: Disable firewalld
  include_tasks: firewalld.yml
  when: firewalld_disable 

- name: Disable selinux
  include_tasks: selinux.yml
  when: selinux_disable 

- name: Setup DNS
  include_tasks: dns.yml
  when: dns_configure 

- name: Check DNS records
  include_tasks: dnscheck.yml
  when: dns_check

- name: Setup loadbalancer
  include_tasks: haproxy.yml
  when: haproxy_configure 

# - name: "check lb settings"

- name: Setup mirror registry
  include_tasks: mirror-registry.yml
  when: registry_configure 

# - name: "import ocp images to mirror registry"

- name: Setup OCP files
  include_tasks: ocp.yml
