---
# - name: "install kvm"

- name: Disable firewalld
  when: firewalld_disable
  ansible.builtin.include_tasks: firewalld.yml

- name: Disable selinux
  when: selinux_disable
  ansible.builtin.include_tasks: selinux.yml

- name: Setup DNS
  when: dns_configure
  ansible.builtin.include_tasks: dns.yml

- name: Check DNS records
  when: dns_check
  args:
    apply:
      delegate_to: 127.0.0.1
  ansible.builtin.include_tasks: dnscheck.yml

- name: Setup loadbalancer
  when: haproxy_configure

  # - name: "check lb settings"
  ansible.builtin.include_tasks: haproxy.yml

- name: Setup NTP Server
  when: ntp_server_configure
  ansible.builtin.include_tasks: ntp-server.yml

- name: Setup mirror registry
  when: registry_configure
  ansible.builtin.include_tasks: mirror-registry.yml

- name: Install Packages
  ansible.builtin.include_tasks: packages.yml

- name: Install clis
  ansible.builtin.include_tasks: setup-cli.yml

- name: Setup OCP files
  when: ocp_configure
  ansible.builtin.include_tasks: ocp.yml

- name: Mirroring from disk to mirror
  when: mirror
  ansible.builtin.include_tasks: mirroring-from-disk-to-mirror.yml
