---
- name: Install podman
  ansible.builtin.yum:
    name: podman
    state: present

- name: Unarchive mirror registry
  ansible.builtin.unarchive:
    src: "{{ mirrorRegistryDir }}"
    dest: "."
    mode: "u+x"

- name: Install mirror registry
  ansible.builtin.command: "./mirror-registry install --quayHostname {{ bastion.name }} --quayRoot ~/images"
  register: registryResult

- name: Print result
  ansible.builtin.debug: 
    var: registryResult