---
- hosts: localhost
  tasks:
  - name: "install podman"
    ansible.builtin.yum:
      name: podman
      state: present

  - name: "tar"
    ansible.builtin.unarchive:
      src: "{{ mirrorRegistryDir }}"
      dest: "."
      mode: "u+x"

  - name: "install"
    ansible.builtin.command: "./mirror-registry install --quayHostname {{ bastion.name }} --quayRoot ~/images"
    register: registryResult
  
  - name: "print"
    ansible.builtin.debug: 
      var: registryResult