---
- name: Install httpd
  ansible.builtin.yum:
    name: httpd
    state: latest

- name: Modify httpd configuration
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: "^Listen"
    line: "Listen 8080"

- name: Check ocp install cli exists
  ansible.builtin.stat:
    path: /usr/local/bin/openshift-install
  register: install_cli

- name: Extract ocp install cli
  ansible.builtin.unarchive:
    src: "{{ ocpInstallDir }}"
    dest: /usr/local/bin/
  when: install_cli.stat.exists == False

- name: Check ocp client cli exists
  ansible.builtin.stat:
    path: /usr/local/bin/oc
  register: client_cli

- name: Extract ocp client cli
  ansible.builtin.unarchive:
    src: "{{ ocpClientDir }}"
    dest: /usr/local/bin/
  when: client_cli.stat.exists == False

- name: Check install dir exists
  ansible.builtin.stat:
    path: /root/ocp4
  register: install_dir

- name: Remove old install dir
  ansible.builtin.file:
    path: /root/ocp4
    state: absent
  when: install_dir.stat.exists == True

- name: Create install dir
  ansible.builtin.file:
    path: /root/ocp4
    state: directory
    mode: 0755

- name: Get pull secret value
  ansible.builtin.command: "cat {{ pullSecretDir }}"
  register: pullsecret

- name: Get ssh key value
  ansible.builtin.command: "cat {{ sshKeyDir }}"
  register: sshkey

- name: Create install config
  ansible.builtin.template:
    src: install-config.j2
    dest: /root/ocp4/install-config.yaml

- name: Generate manifests
  ansible.builtin.command: openshift-install create manifests --dir=/root/ocp4

- name: Modify scheduler config
  ansible.builtin.lineinfile:
    path: /root/ocp4/manifests/cluster-scheduler-02-config.yml
    regexp: "^[\\s]*mastersSchedulable"
    line: "  mastersSchedulable: false"

- name: Generate ignition files
  ansible.builtin.command: openshift-install create ignition-configs --dir=/root/ocp4

- name: Copy the ignition files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/www/html
  with_fileglob:
  - "/root/ocp4/*.ign"

- name: Granted read permission for httpd files
  ansible.builtin.file:
    path: /var/www/html
    state: directory
    recurse: yes
    mode: 0644
  notify:
  - restart httpd
