---
# defaults file for ocp_installer
dns: 168.95.1.1
clusterName: ibm
baseDomain: cp.example
pullSecretDir: /root/pull-secret.txt
sshKeyDir: /root/.ssh/id_rsa.pub 
rawfileDir: /root/rhcos-4.4.3-x86_64-metal.x86_64.raw.gz
ocpInstallDir: /root/openshift-install-linux.tar.gz
ocpClientDir: /root/openshift-client-linux.tar.gz
bastion:
  name: bastion
  ip: 10.9.42.31
bootstrap:
  name: bootstrap
  ip: 10.9.42.32
master:
- name: master0
  ip: 10.9.42.33
- name: master1
  ip: 10.9.42.34
- name: master2
  ip: 10.9.42.35
worker: 
- name: infra
  ip: 10.9.42.36
- name: worker
  ip: 10.9.42.37
