---
# handlers file for ocp_installer
- name: restart dns
  service:
    name: dnsmasq
    state: restarted
    enabled: true

- name: restart haproxy
  service:
    name: haproxy
    state: restarted
    enabled: true

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: true
